version: "3.9"

services:
  tcp-server:
    container_name: tcp-server
    build: .
    #      context: .
    #      dockerfile: ./app/Dockerfile
#    nc 0.0.0.0 11111 | wireshark -k -i -
    ports:
      - 11111:11111
      - 5555:5555
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
